events {}

http {
    # JA4 log (tùy chọn)
    log_format ja4 '$remote_addr [$time_local] JA4=$http_ssl_ja4 "$request"';
    access_log  /etc/nginx/logs/access.log ja4;

    # Kết nối tới FastAPI container cùng mạng
    upstream pizza_api {
        server fastapi:8000;
    }

    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate     /etc/nginx/conf/cert.pem;
        ssl_certificate_key /etc/nginx/conf/key.pem;

        location / {
            # gắn fingerprint
            proxy_set_header X-JA4        $http_ssl_ja4;
            proxy_set_header X-JA4-String $http_ssl_ja4_string;

            # header quen thuộc
            proxy_set_header Host        $host;
            proxy_set_header X-Real-IP   $remote_addr;

            proxy_pass http://pizza_api;
        }
    }

    #  HTTP → HTTPS
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }
}